### ISSUE TITLE
Microsoft Remote Desktop recipe fails in Autopkg 2.7 due to issues with embedded processor

### ISSUE THREAD

**Issue by cfranson** [autopkg/foigus-recipes#100]
MicrosoftRemoteDesktop.munki.recipe is failing to run in Autopkg 2.7 due to issues in the GoogleTalkPlugin/MunkiPkginfoReceiptsEditor:
"Unable to import 'com.github.keeleysam.recipes.GoogleTalkPlugin/MunkiPkginfoReceiptsEditor', likely due to syntax or Python error."
This functionality is now merged into MunkiOptionalReceiptsEditor and doesn't require the use of the GoogleTalkPlugin shared processor:
https://github.com/autopkg/keeleysam-recipes/issues/148#issue-1350421613

**Comment by flammable** [comment]
I tried swapping the processor in-place on line 133, but received this:

```
Processor: MunkiOptionalReceiptEditor: Error: You must specify at least one pkginfo repo path
```

I'm not sure how to fix this. `MUNKI_REPO_SUBDIR` is included on lines 11-12, so I'm not sure why this isn't working.

**Comment by jpiel** [comment]
I saw in MicrosoftOffice365 recipe that adding the following before the processor may fix the issue : 
`      <dict>
            
            <key>Arguments</key>
            <dict>
                <key>predicate</key>
                <string>munki_repo_changed == False</string>
            </dict>
            <key>Processor</key>
            <string>StopProcessingIf</string>
        </dict>        `

**Comment by foigus** [comment]
Examining the code with my very pedestrian python skills seems to say that Sam Keeley's [MunkiPkginfoReceiptsEditor.py](https://github.com/autopkg/keeleysam-recipes/blob/master/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py#L30-L32) just exits when no `pkginfo_repo_path` is supplied:
```
       if len(self.env['pkginfo_repo_path']) < 1:
            self.output('empty pkginfo path')
            return
```
whereas the core [MunkiOptionalReceiptEditor.py](MunkiOptionalReceiptEditor.py) fails when no `pkginfo_repo_path` is supplied:
```
    def main(self):
        if len(self.env["pkginfo_repo_path"]) < 1:
            raise ProcessorError("You must specify at least one pkginfo repo path")
```
`pkginfo_repo_path` is `required`, and it's certainly reasonable that if a `required` variable isn't passed into the processor (e.g. due to [MunkiImporter.py](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L149) it's proper behavior to return a processor error.  But it's also reasonable to expect that recipe authors don't need to manually check for `munki_repo_changed` being `True` and halt recipe execution purely because there was no import of an item into the Munki repo (which is arguably the most common case when using `.munki` recipes, and the situation that the above edit to the MicrosoftOffice365 recipe addresses).

Would the following logic be more reasonable (and note `munki_repo_changed` comes from [MunkiImporter.py](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L149)) upon a successful item import)?
```
if munki_repo_changed = true
then
  if fewer than one pkginfo_repo_path
  then
    fail
  fi
else
  exit success #noop
fi
```

**Comment by jpiel** [comment]
Seems more reasonable to me too..

**Comment by vmiller** [comment]
"It's reasonable for recipe authors to not need to check for munki_repo_changed being set to False and halt recipe execution purely because there was no import of an item into the Munki repo"

I tend to agree with this statement.  I would support a change to the core processor to make it behave more like Sam Keeley's non core processor.  Doing so would make it a drop in replacement.

**Comment by foigus** [comment]
Created an issue [here](https://github.com/autopkg/autopkg/issues/827).

**Comment by kevinmcox** [comment]
Of course I submitted a PR #107 before looking at open issues...

To me I'm not sure why this recipe even needs a Optional Receipt Editor process at all. It creates a Munki installs array which means all package receipts in the PkgInfo will be ignored anyways.

**Comment by foigus** [comment]
IIRC before the `installs` array, there were potential issues with the Microsoft AutoUpdate package receipt potentially being reverted to a version _prior_ to what might have been included in the Remote Desktop package.  But the point of an `installs` array being considered before the receipts is valid, so I accepted PR #107.
