### ISSUE TITLE
Maxon Cinema 4D S26

### ISSUE THREAD

**Issue by svinusje** [autopkg/foigus-recipes#106]
Hi,

if i fill in s26 as the major version i get the message that on "https://www.maxon.net/en/downloads/cinema-4d-s26-downloads" : No match found on URL: https://www.maxon.net/_nuxt/static/1665664419/en/downloads/cinema-4d-s26-downloads/payload.js
Failed.

suggestions?

**Comment by foigus** [comment]
Maxon changed the URL format between the `S##` and year-based (e.g. `2023`) releases. The (first!) `URLTextSearcher` regex for each:

[Year-based](https://github.com/autopkg/foigus-recipes/commit/8388496f7e6c52449547d76b558db5c92feef761):
`https:\\u002F\\u002Fmx-app-blob-prod\.maxon\.net\\u002Fmx-package-production\\u002Finstaller\\u002Fmacos\\u002Fmaxon\\u002Fcinema4d\\u002Freleases\\u002F%MAJOR_VERSION%[\d\.]+\\u002FCinema4D_%MAJOR_VERSION%_%MAJOR_VERSION%[\d\.]+_Mac\.dmg`
[S##-based](https://github.com/autopkg/foigus-recipes/commit/f918c0fe433dd78da62893336eee86893a4961b7):
`https:\\u002F\\u002Fmx-app-blob-prod\.maxon\.net\\u002Fmx-package-production\\u002Finstaller\\u002Fmacos\\u002Fmaxon\\u002Fcinema4d\\u002Freleases\\u002F%MAJOR_VERSION%[\d\.]+\\u002FCinema4D_S%MAJOR_VERSION%_%MAJOR_VERSION%[\d\.]+_Mac\.dmg`

Due to this change (the removal of the "S" in both the URLs and application name), it's not easily possible (_PR's accepted!_) to support both the non-current and current subscription-based releases via `MAJOR_VERSION` (and I really planned `MAJOR_VERSION` to be able to support _future_ releases rather than _past_ ones.).  In addition, since there are three calls to `URLTextSearcher` between the `.download` and `.pkg` recipes, this isn't a situation where it's easy to provide the Cinema 4D installation package via `-d /path/to/the.dmg` since it's nearly guaranteed that one of the `URLTextSearcher` processors will fail.

Best I can suggest is reverting my repo to [this commit](https://github.com/autopkg/foigus-recipes/commit/f918c0fe433dd78da62893336eee86893a4961b7) where the `S##` releases were working up until a few weeks ago when I introduced support for Cinema 4D 2023.

**Comment by foigus** [comment]
Or potentially you could:
- Download the "Subscription" recipes as they stood at the [last functional S## commit](https://github.com/autopkg/foigus-recipes/tree/f918c0fe433dd78da62893336eee86893a4961b7/Maxon)
- Carefully add the files to a location with a higher precedence in the [Recipe Search Order](https://github.com/autopkg/autopkg/wiki/Recipe-Search-Order)
- Run the recipes with `MAJOR_VERSION` set/overridden to `26`

Given that Maxon probably doesn't consider Cinema 4D S26 to be current/developed, I'd not anticipate _too_ many new releases past today.  If you could get the recipe to run _once_ successfully you probably would be OK.
