### ISSUE TITLE
Cinema 4D - Have Maxon changed the URL download?

### ISSUE THREAD

**Issue by markkenny** [autopkg/foigus-recipes#133]
Using  com.github.foigus.pkg.Cinema4DSubscription as ParentRecipe

The following recipes failed:
    com.myco.jamf.autopkg-maxon-cinema4d
        Error in com.myco.jamf.autopkg-maxon-cinema4d: Processor: URLTextSearcher: Error: No match found on URL: https://www.maxon.net/en/downloads/cinema-4d-2023-downloads/

**Comment by Stette** [comment]
It looks like they require users to login before downloading
<img width="592" alt="Screenshot 2023-12-06 at 13 04 46" src="https://github.com/autopkg/foigus-recipes/assets/11584358/c11dadb2-a453-457b-b621-3ad4e59726fd">

**Comment by foigus** [comment]
It looks like Maxon revised their website in the last 24 hours.  I'll see what I can find.

**Comment by foigus** [comment]
I just committed a _lot_ of Maxon-related stuff.  Please update your copy of my repo and try again.

**Comment by Stette** [comment]
Sorry to be the bringer of bad news, but it seems maybe the URL has changed again over the weekend?

`Error in local.munki.Cinema4DPerpetual: Processor: URLTextSearcher: Error: No match found on URL: https://www.maxon.net/en/downloads/cinema-4d-s25-downloads`

**Comment by markkenny** [comment]
Just ran my override and it's working for me, just brought down MAXON-Cinema4D-2024-2024.1.0.pkg.

**Comment by foigus** [comment]
@Stette I'm going to need some help since we no longer use Cinema 4D and I have no pull to enter this question under a support request:

- The fact `cinema-4d-s25-downloads` shows up in the "problematic" URL means you're using the `Perpetual` series of Cinema 4D recipes, rather than the `Subscription` series--are you truly attempting to get the Perpetual release?
- What is the most current Cinema 4D Perpetual license release?  The perpetual sales page says "Cinema 4D S25", but is that truly correct?
- Please include your override in your response

I may have incorrectly aimed [this commit](https://github.com/autopkg/foigus-recipes/commit/fd77c1788c559704b47e57876f7024177bef9087) toward the "S"(ubscription) releases and should have kept it on the "R"(etail) releases.  But I also don't know whether either Cinema 4D 2023 or 2024 either are available as perpetual licenses or have a perpetual release equivalent (e.g. `R27`?).

Let me know what you find.

**Comment by foigus** [comment]
[This](https://support.maxon.net/hc/en-us/articles/1500006434741-What-s-the-difference-between-an-S-version-and-R-Version-) may be helpful (boldfacing and italicizing mine):

---
Cinema 4D versions come in two different licensing options, Subscription (S) and Full Release (R).  If you have an active subscription licence, you are permitted to use both the S and R versions.  If you have a perpetual licence, you are permitted to use up to the release you own.

e.g.
- An R21 Perpetual user can use R21 only.
- An R23 Perpetual user, can use R23, S22 and R21 - they cannot use S24 or onward, as this is a subscription-only release. 
- An R25 Perpetual user can use, R25, S24, R23, S22 and R21, but cannot use S26.
- A subscription customer will be able to use the latest version, either S or R. 
- **_Cinema 4D 2023 removed the S/R and is a subscription only product._**
---

So I'm seeing Cinema 4D 2023+ is a subscription-only product.  Can anyone confirm this statement?

**Comment by Stette** [comment]
Thanks for checking up on this!

It seems not many of my users are still using this software, so I'm just gonna move it out of the automatic override and let it die a slow death there 😂

Thanks again!

**Comment by foigus** [comment]
I fixed the issues [here](https://github.com/autopkg/foigus-recipes/commit/140c6549f4c53458aa7393cd14fef9fd940816dc) with Cinema 4D Perpetual so the recipe runs again, and I then deprecated the recipe entirely [here](https://github.com/autopkg/foigus-recipes/commit/eb60cf3cb114b704c8ed6f4204479f2a08e10de8).
