### ISSUE TITLE
SendtoKindle.download.recipe - Add CodeSignatureVerifier

### ISSUE THREAD

**Issue by blackthroat** [autopkg/foigus-recipes#22]
```
Aug 24 2017 09:31:39 -0500 Install of Send to Kindle-1.0: FAILED with return code: 1

Aug 24 2017 09:31:39 -0500 ERROR: ------------------------------------------------------------------------------
Aug 24 2017 09:31:39 -0500 ERROR: installer: Package name is Send to Kindle for Mac
Aug 24 2017 09:31:39 -0500 ERROR: installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.
Aug 24 2017 09:31:39 -0500 ERROR: ------------------------------------------------------------------------------
```
I would suspect you could use the same code from the commit for your KindlePreviewer.download.recipe (https://github.com/autopkg/foigus-recipes/commit/cec156e2452b93f32204f0a84491a1b3ba97368f) and insert that block after Line 36 on SendtoKindle.download.recipe

**Comment by foigus** [comment]
I can't add CodeSignatureVerifier--since the certificate used to sign the package is expired it would definitely fail:

```
$ pkgutil --check-signature SendToKindleForMac-installer.pkg 
Package "SendToKindleForMac-installer.pkg":
   Status: signed by a certificate that has since expired
   Certificate Chain:
    1. Developer ID Installer: AMZN Mobile LLC
       SHA1 fingerprint: B2 CA 5F 5C 47 B2 8B CF 60 D3 A5 F1 99 91 A5 6D 3F 9A 6D 5C
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
```

In other words, instead of downloading what now is an expired package--if I added CodeSignatureVerifier the `SendtoKindle.download` recipe would completely fail rather than not being as security-conscious as it could be.

In the case of Munki 3, allowing untrusted (in this case expired) packages is [built-in](https://github.com/munki/munki/wiki/Allowing-Untrusted-Packages).  Otherwise the package should be [expanded and flattened](https://managingosx.wordpress.com/2012/03/24/fixing-packages-with-expired-signatures/) to remove the signature and reimported into the management system of choice.  This package hasn't changed since I wrote the recipe, so it shouldn't be overtly painful to strip the package signature.

**Comment by blackthroat** [comment]
Great, thanks for the quick response and the lesson!

So I just added
```
<key>allow_untrusted</key>
<true/>
```
to SendToKindle-1.0.plist after Line 17 and received this error:

```
$ cat /Library/Managed\ Installs/Logs/errors.log
Aug 25 2017 17:11:48 -0500 ERROR: ------------------------------------------------------------------------------
Aug 25 2017 17:11:48 -0500 ERROR: installer: Package name is Send to Kindle for Mac
Aug 25 2017 17:11:49 -0500 ERROR: installer: Installing at base path /
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Preparing for installation…
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Preparing the disk…
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Preparing Send to Kindle for Mac…
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Waiting for other installations to complete…
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Configuring the installation…
Aug 25 2017 17:11:49 -0500 ERROR: installer:STATUS:
Aug 25 2017 17:11:49 -0500 ERROR: installer:%19.382153
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Writing files…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%28.760598
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Writing files…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%48.703257
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%50.326925
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%50.643635
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%54.123892
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Moving items into place…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%86.551799
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%88.130204
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%88.157414
Aug 25 2017 17:11:49 -0500 ERROR: installer:PHASE:Running package scripts…
Aug 25 2017 17:11:49 -0500 ERROR: installer:%97.750000
Aug 25 2017 17:11:49 -0500 ERROR: installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
Aug 25 2017 17:11:49 -0500 ERROR: ------------------------------------------------------------------------------
$ managedsoftwareupdate --version
3.0.3.335
```
Any suggestions? Increase logging level and run it again? Or expand and flatten?

**Comment by gregneagle** [comment]
Did you run `makecatalogs` after your pkginfo edit? 
And then did you run `managedsoftwareupdate` on the client so it could get your changes?
And are your clients running Munki 3.x?

**Comment by blackthroat** [comment]
Yes to all 3 of those questions. The client is running Munki 3.0.3.335.

I did keep a closer eye on the client during the `logoutinstall` process and noticed it had a "Keychain Not Found" message come up that I was not able to click Reset to Defaults.

![image](https://user-images.githubusercontent.com/25038086/29736922-90d2b904-89cb-11e7-8976-67478a8cd9eb.png)

When manually installing the package from Amazon's site (which prompted for admin credentials during installation), the installer asks for a Destination with only one option to select:

![image](https://user-images.githubusercontent.com/25038086/29737131-7b34ebaa-89ce-11e7-9858-ec246ab36f07.png)

After completing, it automatically launches and shows this screen:

![image](https://user-images.githubusercontent.com/25038086/29737042-480dba6e-89cd-11e7-97b4-33aa7afbd0cf.png)

**Comment by gregneagle** [comment]
So `allow_untrusted` did its job and the Installer attempted to install the package. However, it appears preinstall or postinstall scripts in the package make assumptions about the install environment that cause the install to fail. That's a bigger issue to diagnose and possibly solve (and not one I personally need to do, so I'll leave that to others...)

**Comment by foigus** [comment]
A cursory examination of the preinstall and postinstall scripts show a decent amount of wtf, however the only "important" things I can see are:

- Deleting (in the `preinstall`) and recreating (in the `postinstall`) the SendToKindle (`stkPrinter`) print queue
- Disabling killing cupsd in the `preinstall` script
- Disabling the launch of SendToKindle in the `postinstall`

Otherwise requiring a logout to install the software and wiping out nearly all of the preinstall and postinstall scripts would likely be effective. 

[preinstall.txt](https://github.com/autopkg/foigus-recipes/files/1256798/preinstall.txt)
[postinstall.txt](https://github.com/autopkg/foigus-recipes/files/1256799/postinstall.txt)

**Comment by blackthroat** [comment]
Seems like an unnecessary amount of work to make this package function "correctly." I'm okay with not supporting this software in my environment, so feel free to close this issue if you'd like.
